name: Benchmarks

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-15-intel' || matrix.os == 'macos-latest'
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_COLOR: 1
          NONINTERACTIVE: 1
        run: |
          brew analytics off
          brew install libomp
          brew reinstall gcc

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv

      - name: Run benchmarks
        run: |
          uvx nox -s benchmarks
