name: Build wheels
on:
  release:
    types: [ published ]
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

env:
  CIBW_BUILD_VERBOSITY: 2
  CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"
  # Skip PyPy and MUSL builds in any and all jobs
  CIBW_SKIP: "pp* *musllinux*"
  FORCE_COLOR: 3

jobs:
  build_windows_wheels:
    name: Wheels (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build wheels on Windows
        run: pipx run cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: >
            PYBAMMSOLVERS_USE_VCPKG=ON
            VCPKG_ROOT_DIR=C:\vcpkg
            VCPKG_DEFAULT_TRIPLET=x64-windows-static-md
            VCPKG_FEATURE_FLAGS=manifests,registries
            CMAKE_GENERATOR="Visual Studio 17 2022"
            CMAKE_GENERATOR_PLATFORM=x64
          CIBW_ARCHS: AMD64
          CIBW_BEFORE_BUILD: python -m pip install setuptools delvewheel # skip CasADi and CMake
          CIBW_REPAIR_WHEEL_COMMAND: delvewheel repair --add-path C:/Windows/System32 -w {dest_dir} {wheel}
          CIBW_TEST_EXTRAS: "dev"
          CIBW_TEST_COMMAND: |
            python -m pytest {project}/tests
      - name: Upload Windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels_windows
          path: ./wheelhouse/*.whl
          if-no-files-found: error
